### ISSUE TITLE
Bug: Aspect Explorer not seeing fabric-applied aspect

### ISSUE THREAD

**Issue by WhitWaldo** [postsharp/Metalama#341] opened 2024-07-22 17:33 UTC
I've got a fabric applying an aspect to the class shown below. The aspect shows up in Intellisense and I can see the applied aspect output when viewing the Metalama diff or from the "Preview Transformed Code" from the Intellisense aspect, but the Aspect Explorer doesn't see it at all.

![image](https://github.com/user-attachments/assets/1675bb4e-69f8-4648-91b3-8e8189400326)

Using VS Professional 2022 17.10.4 with the VS Metalama tools 2024.2.15.0

**Comment by svick** [comment] 2024-07-24 09:42
I can't reproduce this using a simple fabric adding a type aspect.

Can you provide [logs](https://doc.postsharp.net/metalama/conceptual/configuration/creating-logs) for the `RoslynCodeAnalysisService` and `DevEnv` processes (including setting `trace` to `true`) when this happens?

Thanks.

**Comment by svick** [comment] 2024-09-17 11:02
Since we didn't hear back, I'm going to close this.

But feel free to comment here if you have more info and we can reopen this.

**Closed by svick** 2024-09-17 11:02 UTC
Labels: bug
