### ISSUE TITLE
 CS0234: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by wasyster** [postsharp/Metalama#13] opened 2022-04-20 07:48 UTC
Hi!

I am creating a custom log attribute, and I run into an error when tried to convert parameter object to json. I have the following lines in my code:

    protected InterpolatedStringBuilder BuildInterpolatedString()
    {
        var stringBuilder = new InterpolatedStringBuilder();

        stringBuilder.AddText(meta.Target.Method.Name);

        stringBuilder.AddText("(");

        var i = meta.CompileTime(0);

        foreach (var prop in meta.Target.Parameters)
        {
            var comma = i > 0 ? ", " : "";

            if (prop.RefKind == RefKind.Out)
            {
                stringBuilder.AddText($"{comma}{prop.Name} = <out> ");
            }
            else
            {
                
                stringBuilder.AddText(prop.Name);
                stringBuilder.AddText(" : ");
                var json = System.Text.Json.JsonSerializer.Serialize(prop.Value);
                stringBuilder.AddText(json);
            }

            i++;
        }

        stringBuilder.AddText(")");

        return stringBuilder;
    }
On run I get the following error: CS0234: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)

When I inspect the converted code I found out that the System.Text.Json not got imported it is missing!
The code will not compile even if I write the full namespace like:
var json = System.Text.Json.JsonSerializer.Serialize(prop.Value);

Further inspecting the Metalama generated code contains the full namespace like:
var json = global:: System.Text.Json.JsonSerializer.Serialize(prop.Value);

**Comment by addabis** [comment] 2022-04-20 11:03
Duplicate of postsharp/Metalama.Samples/#7

**Closed** 2022-04-27 10:26 UTC
